// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rczfszhgyvlvzpnybphm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjemZzemhneXZsdnpwbnlicGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODU0NzcsImV4cCI6MjA2MjI2MTQ3N30.27Pxqol6cickovaaMwrK1Xb1jo8KQMmfb6lGe1yUcmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);